# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FurnitureAR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FurnitureAR

pod 'Firebase/Firestore'
pod 'Firebase/Auth'

  target 'FurnitureARTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FurnitureARUITests' do
    # Pods for testing
  end

end
